global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'spring-boot-tracing'

  - job_name: 'tempo'
    static_configs:
      - targets: ['localhost:3200']

  - job_name: 'loki'
    static_configs:
      - targets: ['localhost:3100']
